require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
inherit_gem:
  rubocop-shopify: rubocop.yml
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: "2.5"

Style/ClassAndModuleChildren:
  Exclude:
    - test/**
